### ISSUE TITLE
Doesn't work on the big icon on the site

### ISSUE THREAD

**Issue by olibeniron** [cygaar/old-twitter#3]
I don't think it works on the logo on the page itself? Works on the little icon, but doesn't apply to the big pne.
![image](https://github.com/cygaar/old-twitter/assets/48998606/916c7e4b-001d-40c5-8ccc-4578718103c3)

**Comment by raid5** [comment]
@olibeniron Correct, this is only for the favicon in the tab

**Comment by olibeniron** [comment]
I see. Thanks.
