### ISSUE TITLE
Can't Load into Extension

### ISSUE THREAD

**Issue by simplypitaya** [cygaar/old-twitter#6]
So i'm trying to use this thing by downloading the file and I tried to "Load Unpacked" to make it a extension. Yet it doesn't let me, how do i?

**Comment by cygaar** [comment]
Did you enable the extension?

**Comment by raid5** [comment]
@simplypitaya Also, you need to download the entire contents of this repository and not just a single file.

**Comment by simplypitaya** [comment]
I

**Comment by simplypitaya** [comment]
finally fixed it on my own, anyways, thx for this thing!

**Comment by simplypitaya** [comment]
that's all, also sorry for 2 comments....i was trying to close this.
